---
gui:
  timeFormat: "2006-01-02"
  shortTimeFormat: "15:04"
  nerdFontsVersion: "3"
  skipRewordInEditorWarning: true
  filterMode: substring
git:
  branchLogCmd: "git hist {{branchName}} --max-count 40 --"
  paging:
    externalDiffCommand: difft --display=inline
promptToReturnFromSubprocess: false
customCommands:
  - description: Push (override)
    key: 'P'
    command: git {{.Form.push}} --verbose
    context: files, commits
    loadingText: Reticulating splines...
    stream: false
    showOutput: true
    prompts:
      - type: 'menu'
        title: 'How to push?'
        key: push
        options:
          - value: 'push'
          - value: 'push --force-with-lease'
            description: Who needs history anyways?
          - value: 'push --no-verify'
            description: Pre-commit hooks slow as shit? No worries, i got you
          - value: 'push --no-verify --force-with-lease'
            description: just do it
  - description: Push (override)
    key: 'P'
    command: git {{.Form.push}} --verbose {{with .SelectedLocalBranch}} {{.UpstreamRemote}} {{.Name}} {{end}}
    context: localBranches
    stream: false
    showOutput: true
    prompts:
      - type: 'menu'
        title: 'How to push?'
        key: push
        options:
          - value: 'push'
          - value: 'push --force-with-lease'
            description: Who needs history anyways?
          - value: 'push --no-verify'
            description: Pre-commit hooks slow as shit? No worries, i got you
          - value: 'push --no-verify --force-with-lease'
            description: just do it
  - description: Set upstream to selected local branch
    key: 'U'
    command: git branch --set-upstream-to={{.SelectedLocalBranch.Name}}
    context: localBranches
    loadingText: Setting upstream...
    stream: false
    showOutput: true
